function result = calculate_c(n, alpha, sigma, sigmaStep)
    result = zeros(1,n);
    for k = 1:n
        result(k) = c(k, n, alpha, sigma, sigmaStep);
    end
end

% "c" переписана под индексацию с единицы
function result = c(k, n, alpha, sigma, sigmaStep)
    if n == 1
        result = sigma.^(1-alpha(sigmaStep));
    else
        if k == 1
           result = ((1+sigma).^(2-alpha(sigmaStep)) - ...
               sigma.^(2-alpha(sigmaStep)))./(2-alpha(sigmaStep)) - ...
               ((1+sigma).^(1-alpha(sigmaStep)) - ...
               sigma.^(1-alpha(sigmaStep)))./2;
        elseif k == n
            k = k-1;
            result = -1.*((k+sigma).^(2-alpha(sigmaStep)) - ...
                (k+sigma-1).^(2-alpha(sigmaStep)))./(2-alpha(sigmaStep)) + ...
                (3.*(k+sigma).^(1-alpha(sigmaStep)) - ...
                (k+sigma-1).^(1-alpha(sigmaStep)))./2;
        else
            k = k-1;
            result = ((k+sigma+1).^(2-alpha(sigmaStep)) - ...
                2.*(k+sigma).^(2-alpha(sigmaStep)) + ...
                (k+sigma-1).^(2-alpha(sigmaStep)))./(2-alpha(sigmaStep)) - ...
                ((k+sigma+1).^(1-alpha(sigmaStep)) - 2.* ...
                (k+sigma).^(1-alpha(sigmaStep)) + ...
                (k+sigma-1).^(1-alpha(sigmaStep)))./2;
        end
    end
end